openapi: 3.0.1
info:
  title: SoundCloud Public API Specification
  contact:
    name: Public API strangler
  version: 1.0.0
  termsOfService: https://developers.soundcloud.com/docs/api/terms-of-use
servers:
  - url: https://api.soundcloud.com
tags:
  - name: oauth
    description: Authentication and Authorization Endpoints.
  - name: me
    description: Own User Endpoints.
  - name: playlists
    description: Playlists Endpoints.
  - name: tracks
    description: Tracks Endpoints.
  - name: users
    description: SoundCloud Users Endpoints.
  - name: miscellaneous
    description: Miscellaneous Endpoints.
paths:
  /connect:
    get:
      summary: The OAuth2 authorization endpoint. Your app redirects a user to this endpoint, allowing them to delegate access to their account.
      tags:
        - oauth
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/client_id'
        - $ref: '#/components/parameters/redirect_uri'
        - $ref: '#/components/parameters/response_type'
      responses:
        200:
          description: Success
        401:
          description: 'Error: Unauthorized'
  /oauth2/token:
    post:
      summary: This endpoint accepts POST requests and is used to provision access tokens once a user has authorized your application.
      tags:
        - oauth
      security:
        - ClientId: []
      requestBody:
        description: OAׁuth payload.
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/authorization_code'
                - $ref: '#/components/schemas/client_credentials'
                - $ref: '#/components/schemas/refresh_token'
                - $ref: '#/components/schemas/password'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                client_credentials:
                  $ref: "#/components/examples/ClientCredentials"
        400:
          description: 'Error: Bad Request'
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ErrInvalidGrant"
        401:
          description: 'Error: Unauthorized'

  /me:
    get:
      summary: Returns the authenticated user’s information.
      tags:
        - me
      security:
        - AuthHeader: []
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/User"
        401:
          description: 'Error: Unauthorized'
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ErrorUnauthorized"
    # put:
    #   summary: Returns ?.
    #   tags:
    #     - me
    #   security:
    #     - AuthHeader: []
    #   responses:
    #     200:
    #       description: Success
  /me/activities:
    get:
      summary: Returns the authenticated user's activities.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/Activities"
        401:
          description: 'Error: Unauthorized'
  # /me/activities/all:
  #   get:
  #     summary: Returns a list of activities.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/limit'
  #     responses:
  #       200:
  #         description: Success
  /me/activities/all/own:
    get:
      summary: Recent the authenticated user's activities.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ActivitiesAllOwn"
        401:
          description: 'Error: Unauthorized'
  /me/activities/tracks:
    get:
      summary: Returns the authenticated user's recent track related activities.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ActivitiesTracks"
        401:
          description: 'Error: Unauthorized'
  # /me/activities/tracks/{tag}:
  #   get:
  #     summary: Returns a list of tracks activities.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/tag'
  #       - $ref: '#/components/parameters/limit'
  #     responses:
  #       200:
  #         description: Success
  /me/connections:
    get:
      summary: Returns a list of the authenticated user's connected social accounts.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/Connections"
        401:
          description: 'Error: Unauthorized'
  /me/connections/{connection_id}:
    get:
      summary: Returns the authenticated user's connected social account.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/connection_id'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/Connection"
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ErrorNotFound"
  /me/favorites:
    get:
      summary: Returns a list of favorited or liked tracks of the authenticated user.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/Tracks"
        401:
          description: 'Error: Unauthorized'
  # /me/favorites/{track_id}:
  #   get:
  #     summary: Returns favorite track.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/track_id'
  #     responses:
  #       200:
  #         description: Success
  #       404:
  #         description: Not Found
  #         content:
  #           application/json:
  #             examples:
  #               default:
  #                 $ref: '#/components/examples/ErrorNotFound'
  #   post:
  #     summary: Post favorite track.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/track_id'
  #     responses:
  #       200:
  #         description: Success
  #   put:
  #     summary: Put favorite track.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/track_id'
  #     responses:
  #       200:
  #         description: Success
  #   delete:
  #     summary: Delete favorite track.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/track_id'
  #     responses:
  #       200:
  #         description: Success
  # /me/favorites/ids:
  #   get:
  #     summary: Returns user’s favorites ids.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     responses:
  #       200:
  #         description: Success
  #         content:
  #           application/json:
  #             examples:
  #               default:
  #                 $ref: "#/components/examples/FavoritesIds"
  #       404:
  #         description: The user could not be found
  /me/followings:
    get:
      summary: Returns a list of users who are followed by the authenticated user.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/UserFollowings"
        401:
          description: 'Error: Unauthorized'
  /me/followings/{user_id}:
    get:
      summary: Returns a user who is followed by the authenticated user.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/User"
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
        503:
          description: 'Error: Service Unavailable'
    put:
      summary: Follows a user.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserId'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                200:
                  $ref: '#/components/examples/OK'
                201:
                  $ref: '#/components/examples/User'
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ErrorNotFound"
    # post:
    #   summary: Endpoint to follow another user.
    #   tags:
    #     - me
    #   security:
    #     - AuthHeader: []
    #   parameters:
    #     - $ref: '#/components/parameters/user_id'
    #   responses:
    #     201:
    #       description: Success
    #       content:
    #         application/json:
    #           examples:
    #             200:
    #               $ref: '#/components/examples/OK'
    #             201:
    #               $ref: '#/components/examples/User'
    #     404:
    #       description: Not Found
    #       content:
    #         application/json:
    #           examples:
    #             default:
    #               $ref: '#/components/examples/ErrorNotFound'
    #     500:
    #       description: Internal Server Error
    delete:
      summary: Deletes a user who is followed by the authenticated user.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                200:
                  $ref: '#/components/examples/OK'
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ErrorNotFound"
        422:
          description:   'Error: Unprocessable Entity'
          content:
            application/json:
              examples:
                422:
                  $ref: '#/components/examples/ErrorUnprocessableEntity'
  # /me/followings/tracks:
  #   get:
  #     summary: Returns all the tracks of all the followings of me.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     responses:
  #       200:
  #         description: Success
  /me/followers:
    get:
      summary: Returns a list of users who are following the authenticated user.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/UserFollowers"
        401:
          description: 'Error: Unauthorized'
  /me/followers/{follower_id}:
    get:
      summary: Returns a user who is following the authenticated user.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/follower_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/User'
        401:
          description: 'Error: Unauthorized'
        404:
          description: Not Found
        503:
          description: Service Unavailable
  /me/playlists:
    get:
      summary: Returns user’s playlists (sets).
      description: Returns playlist info, playlist tracks and tracks owner info.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/PlaylistAndTracks"
        401:
          description: 'Error: Unauthorized'
    # post:
    #   summary: Returns user’s favorites ids.
    #   tags:
    #     - me
    #   security:
    #     - AuthHeader: []
    #   responses:
    #     200:
    #       description: Success
  # /me/playlists/{playlist_id}:
  #   get:
  #     summary: Returns playlist.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/playlist_id'
  #     responses:
  #       200:
  #         description: Success
  #   put:
  #     summary: Returns favorite track.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/playlist_id'
  #     responses:
  #       200:
  #         description: Success
  /me/tracks:
    get:
      summary: Returns a list of user's tracks.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/Tracks"
        401:
          description: 'Error: Unauthorized'
  # /me/tracks/{track_id}:
  #   get:
  #     summary: Returns a list of tracks.
  #     tags:
  #       - me
  #     security:
  #       - AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/track_id'
  #     responses:
  #       200:
  #         description: Success
  /me/web-profiles:
    get:
      summary: Returns a list of the authenticated user's links added to their profile.
      tags:
        - me
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/Web-profiles"
        401:
          description: 'Error: Unauthorized'
  /playlists:
    get:
      summary: Returns a list of playlists with tracks included in response.
      tags:
        - playlists
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: "#/components/parameters/q"
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/PlaylistAndTracks"
        400:
          description: 'Error: Bad Request'
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ErrInvalidRequest"
        401:
          description: 'Error: Unauthorized'
  #   post:
  #     summary: Returns  error ???.
  #     tags:
  #       - playlists
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     responses:
  #       200:
  #         description: Success
  # /playlists/{playlist_id}:
  #   get:
  #     summary: Returns a playlist.
  #     tags:
  #       - playlists
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: "#/components/parameters/playlist_id"
  #     responses:
  #       200:
  #         description: Success
  #   put:
  #     summary: Creates a playlist.
  #     tags:
  #       - playlists
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: "#/components/parameters/playlist_id"
  #     responses:
  #       200:
  #         description: Success
  #   delete:
  #     summary: Deletes a playlist.
  #     tags:
  #       - playlists
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: "#/components/parameters/playlist_id"
  #     responses:
  #       200:
  #         description: Success
  # /playlists/{playlist_id}/tracks:
  #   get:
  #     summary: Returns playlist's tracks.
  #     tags:
  #       - playlists
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: "#/components/parameters/playlist_id"
  #     responses:
  #       200:
  #         description: Success
  # /tracks:
  #   get:
  #     summary: Returns ???.
  #     tags:
  #       - tracks
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     responses:
  #       200:
  #         description: Success
    # post:
    #   summary: Returns ???.
    #   tags:
    #     - tracks
    #   security:
    #     - ClientId: []
    #       AuthHeader: []
    #   responses:
    #     200:
    #       description: Success
  /tracks/{track_id}:
    get:
      summary: Returns a track.
      tags:
        - tracks
      security:
        - ClientId: []
      parameters:
        - $ref: '#/components/parameters/track_id'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/Track'
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/ErrorNotFound'
    put:
      summary: Updates a track's information.
      tags:
        - tracks
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/track_id'
      requestBody:
        description: Track payload
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTrackRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/Track'
        400:
          description: 'Error: Bad Request'
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/ErrorInvalidRequest'
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/ErrorNotFound'
        500:
          description: 'Error: Internal Server Error'
    delete:
      summary: Deletes a track.
      tags:
        - tracks
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/track_id'
      responses:
        200:
          description: Success
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
  /tracks/{track_id}/comments:
    get:
      summary: Returns the comments posted on the track(track_id).
      tags:
        - tracks
      security:
        - ClientId: []
      parameters:
        - $ref: '#/components/parameters/track_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/Comments'
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/ErrorNotFound'
    # post:
    #   summary: Returns ???.
    #   tags:
    #     - tracks
    #   security:
    #     - ClientId: []
    #       AuthHeader: []
    #   parameters:
    #     - $ref: '#/components/parameters/track_id'
    #   responses:
    #     200:
    #       description: Success
  # /tracks/{track_id}/comments/{comment_id}:
  #   get:
  #     summary: Returns ???.
  #     tags:
  #       - tracks
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/track_id'
  #       - $ref: '#/components/parameters/comment_id'
  #     responses:
  #       200:
  #         description: Success
  #       404:
  #         description: 'Error: Not Found'
  #   delete:
  #     summary: Returns ???.
  #     tags:
  #       - tracks
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/track_id'
  #       - $ref: '#/components/parameters/comment_id'
  #     responses:
  #       200:
  #         description: Success
  # /tracks/{track_id}/download:
  #   get:
  #     summary: Returns ???.
  #     tags:
  #       - tracks
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/track_id'
  #     responses:
  #       200:
  #         description: Success
  /tracks/{track_id}/favoriters:
    get:
      summary: Returns a list of users who have favorited or liked the track.
      tags:
        - tracks
      security:
        - ClientId: []
      parameters:
        - $ref: '#/components/parameters/track_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/Users'
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/ErrorNotFound'
  /tracks/{track_id}/favoriters/{user_id}:
    get:
      summary: Returns a user who has favorited or liked the track.
      tags:
        - tracks
      security:
        - AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/track_id'
        - $ref: '#/components/parameters/user_id'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/User'
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/ErrorNotFound'
  /tracks/{track_id}/related:
    get:
      summary: Returns all related tracks of track on SoundCloud.
      tags:
        - tracks
      security:
        - ClientId: []
      parameters:
        - $ref: '#/components/parameters/track_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/Tracks'
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: '#/components/examples/ErrNotFound'
  # /tracks/{track_id}/streams:
  #   get:
  #     summary: Returns ???.
  #     tags:
  #       - tracks
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/track_id'
  #     responses:
  #       200:
  #         description: Success
  /resolve:
    get:
      summary: Resolves soundcloud.com URLs to Resource URLs to use with the API.
      tags:
        - miscellaneous
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/url'
      responses:
        200:
          description: Success
  # /users:
  #   get:
  #     summary: Returns users list.
  #     tags:
  #       - users
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     responses:
  #       200:
  #         description: Success
  /users/{user_id}:
    get:
      summary: Returns a user.
      tags:
        - users
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/User"
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ErrorNotFound"
    # put:
    #   summary: Returns user's information.
    #   tags:
    #     - user
    #   security:
    #     - ClientId: []
    #       AuthHeader: []
    #   parameters:
    #     - $ref: '#/components/parameters/user_id'
    #   responses:
    #     200:
    #       description: Success
  /users/{user_id}/comments:
    get:
      summary: Returns a list of user's comments.
      tags:
        - users
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/Comments"
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ErrorNotFound"
  /users/{user_id}/favorites:
    get:
      summary: Returns a list of user's favorited or liked tracks.
      tags:
        - users
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/Tracks"
        401:
          description: 'Error: Unauthorized'
  # /users/{user_id}/favorites/{track_id}:
  #   get:
  #     summary: Returns user's favorite track.
  #     tags:
  #       - users
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/user_id'
  #       - $ref: '#/components/parameters/track_id'
  #     responses:
  #       200:
  #         description: Success
  /users/{user_id}/followers:
    get:
      summary: Returns a list of user’s followers.
      description: Returns a list of users that follows (user_id).
      tags:
        - users
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/UserFollowers"
        401:
          description: 'Error: Unauthorized'
        503:
          description: 'Error: Service Unavailable'
  /users/{user_id}/followers/{follower_id}:
    get:
      summary: Returns a user's follower.
      description: Returns a (follower's user_id) that follows (user_id).
      tags:
        - users
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/follower_id'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/User"
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
        503:
          description: 'Error: Service Unavailable'
  /users/{user_id}/followings:
    get:
      summary: Returns a list of user’s followings.
      description: Returns list of users that (user_id) follows.
      tags:
        - users
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/UserFollowings"
        401:
          description: 'Error: Unauthorized'
        503:
          description: 'Error: Service Unavailable'
  /users/{user_id}/followings/{following_id}:
    get:
      summary: Returns a user's following.
      description: Returns (following_id) that is followed by (user_id).
      tags:
        - users
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/following_id'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/User"
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
        503:
          description: 'Error: Service Unavailable'
  /users/{user_id}/playlists:
    get:
      summary: Returns a list of user's playlists.
      tags:
        - users
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/PlaylistAndTracks"
        401:
          description: 'Error: Unauthorized'
  # /users/{user_id}/playlists/{track_id}:
  #   get:
  #     summary: Returns user's playlists list.
  #     tags:
  #       - users
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/user_id'
  #       - $ref: '#/components/parameters/track_id'
  #     responses:
  #       200:
  #         description: Success
  /users/{user_id}/tracks:
    get:
      summary: Returns a list of user's tracks.
      tags:
        - users
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/Tracks"
        401:
          description: 'Error: Unauthorized'
  # /users/{user_id}/tracks/{track_id}:
  #   get:
  #     summary: Returns user's track.
  #     tags:
  #       - users
  #     security:
  #       - ClientId: []
  #         AuthHeader: []
  #     parameters:
  #       - $ref: '#/components/parameters/user_id'
  #       - $ref: '#/components/parameters/track_id'
  #     responses:
  #       200:
  #         description: Success
  /users/{user_id}/web-profiles:
    get:
      summary: Returns list of user's links added to their profile (website, facebook, instagram).
      tags:
        - users
      security:
        - ClientId: []
          AuthHeader: []
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Success
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/Web-profiles"
        401:
          description: 'Error: Unauthorized'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              examples:
                default:
                  $ref: "#/components/examples/ErrorNotFound"
components:
  parameters:
    client_id:
      in: query
      name: client_id
      required: true
      schema:
        type: string
      description: client_id
    comment_id:
      in: path
      name: comment_id
      required: true
      schema:
        type: integer
      description: SoundCloud comment id
    connection_id:
      in: path
      name: connection_id
      required: true
      schema:
        type: integer
      description: SoundCloud connection id
    limit:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
      description: Number of results to return in the collection.
    follower_id:
      in: path
      name: follower_id
      required: true
      schema:
        type: integer
      description: SoundCloud User id to denote a Follower
    following_id:
      in: path
      name: following_id
      required: true
      schema:
        type: integer
      description: SoundCloud User id to denote a Following of a user
    playlist_id:
      in: path
      name: playlist_id
      required: true
      schema:
        type: integer
      description: SoundCloud playlist id
    q:
      in: query
      name: q
      required: true
      schema:
        type: string
      description: search
    redirect_uri:
      in: query
      name: redirect_uri
      required: true
      schema:
        type: string
      description: redirect_uri
    response_type:
      in: query
      name: response_type
      required: true
      schema:
        type: string
        enum:
          - code
          - token
          - code_and_token
      description: response type
    tag:
      in: path
      name: tag
      required: true
      schema:
        type: string
      description: tag
    track_id:
      in: path
      name: track_id
      required: true
      schema:
        type: integer
      description: SoundCloud Track id
    url:
      in: query
      name: url
      required: true
      schema:
        type: string
      description: SoundCloud URL
    user_id:
      in: path
      name: user_id
      required: true
      schema:
        type: integer
      description: SoundCloud User id
  securitySchemes:
    ClientId:
      in: query
      type: apiKey
      name: client_id
      description: Your product key. This is not the same as the API key used for most requests
    AuthHeader:
      in: header
      type: apiKey
      name: Authorization
      description: 'The string "OAuth" followed by the user’s token: OAuth ACCESS_TOKEN'
  schemas:
    authorization_code:
      type: object
      properties:
        grant_type:
          type: string
          enum:
            - authorization_code
            - client_credentials
        authorization_code:
          type: string
          description: Authorization code
        client_id:
          type: string
          description: Client ID
        redirect_uri:
          type: string
          description: Redirect URI
        client_secret:
          type: string
          description: Client secret
    client_credentials:
      allOf:
      - $ref: "#/components/schemas/authorization_code"
    refresh_token:
      type: object
      properties:
        grant_type:
          type: string
          enum:
            - refresh_token
        refresh_token:
          type: string
          description: Refresh token
        client_id:
          type: string
          description: Client ID
        redirect_uri:
          type: string
          description: Redirect URI
        client_secret:
          type: string
          description: Client secret
    password:
      type: object
      properties:
        grant_type:
          type: string
          enum:
            - password
        user_name:
          type: string
          description: User name
        password:
          type: string
          description: User password
        client_id:
          type: string
          description: Client ID
        redirect_uri:
          type: string
          description: Redirect URI
        client_secret:
          type: string
          description: Client secret
    UpdateTrackRequest:
      type: object
      properties:
        track:
          type: object
          properties:
            title:
              type: string
            permalink:
              type: string
            sharing:
              type: string
              enum:
                - public
                - private
              default: public
            embeddable_by:
              type: string
              enum:
                - all
                - me
                - none
              description: 'who can embed this track "all", "me", or "none"'
            purchase_url:
              type: string
            description:
              type: string
            genre:
              type: string
            tag_list:
              type: string
              description: "The tag_list property contains a list of tags separated by spaces. Multiword tags are quoted in doublequotes. We also support machine tags that follow the pattern NAMESPACE:KEY=VALUE. For example: geo:lat=43.555
                camel:size=medium
                “machine:tag=with space”
                Machine tags are not revealed to the user on the track pages."
            label_name:
              type: string
            release:
              type: string
            release_date:
              title: write only!
              type: string
              description: string, formatted as yyyy-mm-dd, representing release date
            streamable:
              type: boolean
              default: true
            downloadable:
              type: boolean
              default: true
            license:
              type: string
              enum:
                - no-rights-reserved
                - all-rights-reserved
                - cc-by
                - cc-by-nc
                - cc-by-nd
                - cc-by-sa
                - cc-by-nc-nd
                - cc-by-nc-sa
              description: 'Possible values: no-rights-reserved, all-rights-reserved, cc-by, cc-by-nc, cc-by-nd, cc-by-sa, cc-by-nc-nd, cc-by-nc-sa'
            commentable:
              type: boolean
              default: true
            isrc:
              type: string
            artwork_data:
              title: only for uploading, for PRO users
              type: string
            asset_data:
              title: Only for uploading
              type: string
    UserId:
      type: object
      properties:
        user_id:
          type: integer
  examples:
    Activities:
      value:
        collection:
          - type: track
            created_at: 2020/10/12 12:02:44 +0000
            origin:
              allOf:
              - $ref: "#/components/examples/Track/value"
          - type: playlist
            created_at: 2020/10/12 12:02:44 +0000
            origin:
              allOf:
              - $ref: "#/components/examples/Track/value"
        next_href: https://api.soundcloud.com/me/activities?limit=10&cursor=00000
        future_href: https://api.soundcloud.com/me/activities?limit=10&cursor=000001
    ActivitiesAllOwn:
      value:
        collection:
          - type: track
            created_at: 2020/10/12 12:02:44 +0000
            origin:
              allOf:
              - $ref: "#/components/examples/Track/value"
          - type: playlist
            created_at: 2020/10/12 12:02:44 +0000
            origin:
              allOf:
              - $ref: "#/components/examples/Track/value"
        next_href: https://api.soundcloud.com/me/activities/all/own?limit=10&cursor=00000
        future_href: https://api.soundcloud.com/me/activities/all/own?limit=10&cursor=000001
    ActivitiesTracks:
      value:
        collection:
          - type: track
            created_at: 2020/10/12 12:02:44 +0000
            origin:
              allOf:
              - $ref: "#/components/examples/Track/value"
          - type: playlist
            created_at: 2020/10/12 12:02:44 +0000
            origin:
              allOf:
              - $ref: "#/components/examples/Track/value"
        next_href: https://api.soundcloud.com/me/activities/tracks?limit=10&cursor=00000
        future_href: https://api.soundcloud.com/me/activities/tracks?limit=10&cursor=000001
    ClientCredentials:
      value:
        access_token: some string
        expires_in: 21599
        scope: ''
        refresh_token: some string
    Comment:
      value:
        body: comment body
        created_at: 2007/09/11 15:40:24 +0000
        id: 1234
        kind: comment
        timestamp: 4960
        track_id: 123456
        uri: https://api.soundcloud.com/comments/1234
        user:
          id: 12345
          kind: user
          permalink: permalink
          username: user name
          last_modified: 2017/04/10 14:48:03 +0000
          uri: https://api.soundcloud.com/users/12345
          permalink_url: https://soundcloud.com/permalink
          avatar_url: https://i1.sndcdn.com/avatars-large.jpg
          followers_count: 138
          followings_count: 172
          public_favorites_count: 5
          reposts_count: 0
        user_id: 12345
    Comments:
      value:
        - allOf:
          - $ref: "#/components/examples/Comment/value"
    Connection:
      value:
        created_at: 1995/07/24 08:55:02 +0000
        display_name: Full Name
        id: 1234
        kind: connection
        post_favorite: true
        post_publish: true
        service: google_plus
        type: google_plus
        uri: https://api.soundcloud.com/connections/1234
    Connections:
      value:
        - allOf:
          - $ref: "#/components/examples/Connection/value"
    Created:
      value:
        status: 201 - Created
    ErrInvalidGrant:
      value:
        error_code: invalid_grant
    ErrInvalidRequest:
      value:
        error: invalid request
    ErrorInvalidRequest:
      value:
        errors:
        - error_message: 400 - Invalid Request
    ErrorUnauthorized:
      value:
        errors:
        - error_message: 401 - Unauthorized
    ErrorNotFound:
      value:
        errors:
        - error_message: 404 - Not Found
    ErrNotFound:
      value:
        error: Not Found
    ErrorUnprocessableEntity:
      value:
        errors:
        - error_message: 422 - Unprocessable Entity
    FavoritesIds:
      value:
        - 1234
        - 5678
        - 3456
    OK:
      value:
        status: Status(200) - OK
    UserFollowings:
      value:
        collection:
          - 
            allOf:
              - $ref: "#/components/examples/User/value"
        next_href: https://api.soundcloud.com/users/1234/followings?client_id=client_id&page_size=10&cursor=1234567
    UserFollowers:
      value:
        collection:
          - 
            allOf:
              - $ref: "#/components/examples/User/value"
        next_href: https://api.soundcloud.com/users/1234/followers?client_id=client_id&page_size=10&cursor=1234567
    Playlist:
      value:
        artwork_url: ''
        created_at: 2020/07/16 16:09:54 +0000
        description:
        downloadable: true
        duration: 11000
        ean:
        embeddable_by: all
        genre: ''
        id: 12345
        kind: playlist
        label:
        label_id:
        label_name:
        last_modified: 2020/09/08 09:13:00 +0000
        license: all-rights-reserved
        likes_count: 0
        permalink: permalink
        permalink_url: https://soundcloud.com/userPermalink/sets/permalink
        playlist_type: ''
        purchase_title:
        purchase_url:
        release:
        release_day:
        release_month:
        release_year:
        sharing: public
        streamable: true
        tag_list: ''
        tags: ''
        title: permalink
        track_count: 2
        tracks_uri: https://api.soundcloud.com/playlists/12345/tracks
        type: ''
        uri: https://api.soundcloud.com/playlists/12345
        user:
          permalink_url: https://soundcloud.com/uesrPermalink
          permalink: userPermalink
          username: user.name
          uri: https://api.soundcloud.com/users/1234
          last_modified: 2020/09/03 14:08:25 +0000
          id: 1234
          kind: user
          avatar_url: https://i1.sndcdn.com/avatars-test-large.jpg
        user_id: 1234
    PlaylistAndTracks:
      value:
        artwork_url: ''
        created_at: 2020/01/16 16:09:54 +0000
        description:
        downloadable:
        duration: 110000
        ean:
        embeddable_by: all
        genre: ''
        id: 12345
        kind: playlist
        label:
        label_id:
        label_name:
        last_modified: 2020/01/08 09:13:00 +0000
        license: all-rights-reserved
        likes_count: 0
        permalink: permalink
        permalink_url: https://soundcloud.com/permalink/sets/club
        playlist_type: ''
        purchase_title:
        purchase_url:
        release:
        release_day:
        release_month:
        release_year:
        sharing: public
        streamable: true
        tag_list: ''
        tags: ''
        title: some title
        track_count: 1
        tracks:
          - allOf:
            - $ref: "#/components/examples/Track/value"
        tracks_uri: https://api.soundcloud.com/playlists/12345/tracks
        type: ''
        uri: https://api.soundcloud.com/playlists/12345
        user:
          permalink_url: https://soundcloud.com/permalink
          permalink: permalink
          username: user.name
          uri: https://api.soundcloud.com/users/12345
          last_modified: 2020/09/03 14:08:25 +0000
          id: 12345
          kind: user
          avatar_url: https://i1.sndcdn.com/avatars-large.jpg
        user_id: 1234
    Track:
      value:
        artwork_url: https://i1.sndcdn.com/artworks-large.jpg
        available_country_codes:
        bpm:
        comment_count: 4
        commentable: true
        created_at: 2019/01/15 15:40:49 +0000
        description:
        domain_lockings:
        download_count: 0
        download_url: https://api.soundcloud.com/tracks/1234/download
        downloadable: false
        downloads_remaining:
        duration: 40000
        embeddable_by: all
        favoritings_count: 271
        genre: Rock
        id: 1234
        isrc:
        key_signature:
        kind: track
        label:
        label_id:
        label_name: some label
        last_modified: 2020/02/05 05:56:22 +0000
        license: all-rights-reserved
        original_content_size: 716981
        original_format: wav
        permalink: permalink
        permalink_url: https://soundcloud.com/userPermalink/trackPermalink
        playback_count: 8027
        purchase_title:
        purchase_url:
        release:
        release_day: 22
        release_month: 8
        release_year: 2019
        reposts_count: 18
        secret_token:
        secret_uri:
        sharing: public
        state: finished
        stream_url: https://api.soundcloud.com/tracks/1234/stream
        streamable: true
        tag_list: ''
        title: Some title
        track_type:
        uri: https://api.soundcloud.com/tracks/1234
        user:
          id: 123456
          kind: user
          permalink: permalink
          username: user.name
          last_modified: 2020/01/10 21:36:49 +0000
          uri: https://api.soundcloud.com/users/123456
          permalink_url: https://soundcloud.com/permalink
          avatar_url: https://i1.sndcdn.com/avatars.jpg
        user_favorite: true
        user_id: 123456
        user_playback_count: 1
        user_uri: https://api.soundcloud.com/users/123456
        video_url:
        waveform_url: https://wave.sndcdn.com/someString.png
    Tracks:
      value:
        - allOf:
          - $ref: "#/components/examples/Track/value"
    User:
      value:
        avatar_url: https://i1.sndcdn.com/avatars.jpg
        city: City
        comments_count: 9
        country: Country
        description:
        discogs_name:
        first_name: First_name
        followers_count: 0
        followings_count: 0
        full_name: Full Name
        id: 12345
        kind: user
        last_modified: 2020/01/03 12:08:25 +0000
        last_name: Last_name
        likes_count: 0
        locale: en
        myspace_name:
        online: false
        permalink: permalink
        permalink_url: https://soundcloud.com/permalink
        plan: Free
        playlist_count: 3
        primary_email_confirmed: true
        private_playlists_count: 0
        private_tracks_count: 0
        public_favorites_count: 20
        quota:
          unlimited_upload_quota: false
          upload_seconds_used: 0
          upload_seconds_left: 10800
        reposts_count: 0
        subscriptions:
        - product:
            id: some-id
            name: some.name
        track_count: 0
        upload_seconds_left: 10800
        uri: https://api.soundcloud.com/users/1234
        username: some.user
        website:
        website_title:
    Users:
      value:
        - allOf:
          - $ref: "#/components/examples/User/value"
    Web-profiles:
      value:
        - created_at: 1995/10/20 12:10:39 +0000
          id: 1234
          kind: web-profile
          service: facebook
          title: my facebook
          url: http://facebook.com
          username: username